CREATE EXTENSION IF NOT EXISTS VECTOR;
CREATE EXTENSION IF NOT EXISTS AI;
CREATE EXTENSION IF NOT EXISTS VECTORSCALE; 

CREATE TABLE IF NOT EXIST document_embedding(
    ID UUID PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    EMBEDDING VECTOR(3072),
);

CREATE TABLE IF NOT EXISTS summaries(
    ID UUID PRIMARY KEY,
    SUMMARY TEXT,
    QUETION TEXT  
)